"""The claims register: every sentence on the site that says how a number is
computed, and the code that makes it true.

Why this exists
---------------
On 2026-10-06 the drilldown's **first sentence**, shown for all 502 stocks, read:

    Ranks 1st of 502. Its composite of 73.8 is a percentile: it scores above
    74% of the universe.

For the stock ranked **1st of 502**. ``Composite`` has been the *cardinal*
weighted average of the category scores since Phase 13 (F1) and the percentile
is the separate ``Composite_Pct`` column, so the claim was wrong by a median of
**19.6 percentage points** across the universe, by more than 10 points for
**74.9%** of stocks, and by **31.2** at worst
(``research/measurements/2026-10-06-rank-sentence-claim.py``, re-measured
2026-10-07).

It had been live for months, and the reason is the part worth engineering
against: **there was a test asserting it.**
``tests/test_stock_summary.py::test_composite_is_described_as_a_universe_percentile``
asserted the sentence said "above 75% of the universe" and cited
``SCREENER_OVERVIEW.md`` as its authority - while the *same* methodology page's
Limitation 8 said the opposite. Correcting the sentence would have looked like a
regression. A claim is only ever as good as the thing that checks it, and a
check pointed at the wrong authority is worse than none.

``scripts/check_published_claims.py`` could not catch it either, because it
tests "specific claims people thought to write down". The gap was structural:
nothing enumerated the *set* of computational claims the site makes, so nothing
could notice one of them was unchecked.

What this module is
-------------------
A single table. Each :class:`Claim` names

* the **surface** the sentence appears on,
* what it **asserts** about how a number is computed, in plain English,
* the code that **makes it true** (``module:qualname``), and
* the test that **checks it**.

``tests/test_claims_register.py`` then enforces the properties that make it a
tripwire rather than documentation:

1. every sentence builder in ``stock_summary.py`` is registered - so adding a
   ``_sentence_*`` function fails the suite until its claim is written down;
2. every ``made_true_by`` resolves to a real attribute of a real module;
3. every ``checked_by`` names a test function that actually exists;
4. every ``detect`` pattern still matches its surface - so silently rewording a
   registered sentence makes the register stale *loudly*; and
5. no :data:`FORBIDDEN` pattern appears in anything published - the direct
   regression guard on the four false statements fixed on 2026-10-07.

Scope, deliberately
-------------------
Claim-shaped vocabulary ("percentile", "weighted", "median", "average",
"discount") appears in hundreds of sentences across a 55 KB methodology page.
Requiring a register entry for every one of them would produce a register
nobody maintains. So the enumerated surfaces are the ones that **state the
arithmetic of a published number**: the per-stock summary sentences, and the
numbered Steps plus the composite/coverage rules on the generated methodology
page. ``FORBIDDEN`` is the complement and applies everywhere.

Stage T0a of ``plan/calculation-transparency.md``. T1 extends this with the
per-metric lineage registry; the two are meant to converge.
"""

from __future__ import annotations

import importlib
from dataclasses import dataclass, field

# --- surfaces -------------------------------------------------------------
# Where a claim is published. Kept as constants so a typo is an AttributeError
# rather than a claim that silently matches nothing.
SUMMARY = "stock_summary"           # baked into stock_detail[t]["summary"]
OVERVIEW = "SCREENER_OVERVIEW.md"   # generated by run_screener, served in index.html
README = "README.md"
DRILLDOWN = "dashboard drilldown (rendered from the payload by the page)"


@dataclass(frozen=True)
class Claim:
    """One sentence-template that states how a number is computed."""

    id: str
    surface: str
    #: What the sentence tells the reader, in plain English.
    asserts: str
    #: ``module:qualname`` - the code that makes it true.
    made_true_by: str
    #: ``tests/test_x.py::test_y`` entries that assert it.
    checked_by: tuple[str, ...]
    #: Regex that must be found in the surface's text. ``None`` for surfaces
    #: whose text is assembled per stock and checked by ``checked_by`` instead.
    detect: str | None = None
    #: Known limits of the claim - recorded so the next stage inherits them
    #: rather than rediscovering them.
    caveat: str = ""

    def resolve(self):
        """Import ``made_true_by`` and return the attribute, or raise."""
        module_name, _, qualname = self.made_true_by.partition(":")
        obj = importlib.import_module(module_name)
        for part in qualname.split("."):
            obj = getattr(obj, part)
        return obj


# ---------------------------------------------------------------------------
# The register
# ---------------------------------------------------------------------------
# One entry per sentence builder in stock_summary.py, plus the methodology
# page's arithmetic claims. `asserts` is what a sceptical reader would be
# entitled to check.

CLAIMS: tuple[Claim, ...] = (
    # --- the per-stock summary ------------------------------------------
    Claim(
        id="summary.rank",
        surface=SUMMARY,
        asserts=(
            "The stock's rank, the share of the *other* stocks it is ahead of as "
            "(N - rank) / (N - 1), and that the composite is a 0-100 score built "
            "from this stock's own category scores and their weights - explicitly "
            "NOT a percentile."
        ),
        made_true_by="stock_summary:_sentence_rank",
        checked_by=(
            "tests/test_stock_summary.py::test_composite_is_not_described_as_a_percentile",
            "tests/test_stock_summary.py::test_rank_share_is_derived_from_the_rank_not_the_composite",
            "tests/test_stock_summary.py::test_category_count_in_the_rank_sentence_is_this_stocks_own_count",
            "tests/test_claims_register.py::test_rank_share_is_exact_for_every_published_stock",
        ),
        caveat=(
            "States that the composite is *computed from* the category scores and "
            "weights, not that it *equals* their weighted average - the coverage "
            "discount reduces it for 3 of 502 stocks (FDXF, PSKY, L on 2026-10-07). "
            "Fixed 2026-10-07 (T0b): the payload now carries the coverage figure "
            "and the drilldown shows the whole chain - category points, the "
            "discount, the composite - so it sums on screen. The sentence still "
            "describes construction rather than asserting an equality, deliberately."
        ),
    ),
    Claim(
        id="summary.drivers",
        surface=SUMMARY,
        asserts=(
            "The two categories with the largest *contributions* (score x effective "
            "category weight), each with its category score and points, and their "
            "sum against the composite. The points are read from the engine's own "
            "`contrib`, never recomputed from the headline weights - that "
            "recomputation was the 2026-08-28 defect."
        ),
        made_true_by="stock_summary:_sentence_drivers",
        checked_by=(
            "tests/test_stock_summary.py::test_drivers_are_the_two_largest_contributors_with_exact_points",
        ),
        caveat=(
            "'X of its Y points' compares a sum of contributions against the "
            "composite, so for the 3 coverage-discounted stocks the two numbers "
            "are on marginally different bases. Fixed 2026-10-07 (T0b) in the sense "
            "that matters: the drilldown shows the discount as its own line, so the "
            "reader can see why."
        ),
    ),
    Claim(
        id="summary.weakest",
        surface=SUMMARY,
        asserts=(
            "The lowest *category score* the stock has (not the lowest "
            "contribution), its points, and that a category score near 50 is the "
            "sector median."
        ),
        made_true_by="stock_summary:_sentence_weakest",
        checked_by=(
            "tests/test_stock_summary.py::test_weakest_is_the_lowest_category_score_not_the_lowest_contribution",
        ),
    ),
    Claim(
        id="summary.best_inputs",
        surface=SUMMARY,
        asserts=(
            "Inside the highest-contributing category, the two weighted metrics "
            "with the highest **sector** percentiles. Percentiles are "
            "direction-adjusted, so inverted metrics carry 'lower is better'."
        ),
        made_true_by="stock_summary:_sentence_best_inputs",
        checked_by=(
            "tests/test_stock_summary.py::test_best_inputs_come_from_the_leading_category_only",
            "tests/test_percentile_direction.py::test_inverted_metric_prose_states_the_direction",
        ),
    ),
    Claim(
        id="summary.worst_input",
        surface=SUMMARY,
        asserts=(
            "The single lowest sector percentile among all weighted metrics with a "
            "value, across every scored category."
        ),
        made_true_by="stock_summary:_sentence_worst_input",
        checked_by=(
            "tests/test_stock_summary.py::test_worst_input_is_the_lowest_percentile_weighted_metric_anywhere",
        ),
    ),
    Claim(
        id="summary.change",
        surface=SUMMARY,
        asserts=(
            "Rank movement, and composite movement when it is at least 0.05, "
            "against a named dated baseline run chosen by `_pick_comparison` "
            "(the ~1-month window in preference to the previous run)."
        ),
        made_true_by="stock_summary:_sentence_change",
        checked_by=(
            "tests/test_stock_summary.py::test_change_prefers_the_one_month_baseline_over_the_previous_run",
        ),
    ),
    Claim(
        id="summary.change_driver",
        surface=SUMMARY,
        asserts=(
            "The category whose score moved furthest in absolute terms since the "
            "same baseline, and what that category now contributes of the "
            "composite. Names the category *score* explicitly, because a falling "
            "Risk score means rising risk."
        ),
        made_true_by="stock_summary:_sentence_change_driver",
        checked_by=(
            "tests/test_stock_summary.py::test_change_driver_names_the_largest_absolute_category_move",
        ),
    ),
    Claim(
        id="summary.input_churn",
        surface=SUMMARY,
        asserts=(
            "That at least MIN_INPUT_CHURN (2) metric inputs appeared or "
            "disappeared since the baseline, so part of the move is the input set "
            "changing rather than the company. Worded as a caveat on the move and "
            "never as deterioration."
        ),
        made_true_by="stock_summary:_sentence_input_churn",
        checked_by=(
            "tests/test_input_churn.py::test_build_summary_includes_the_fact",
            "tests/test_input_churn.py::test_build_summary_omits_it_below_the_threshold",
        ),
    ),
    Claim(
        id="summary.target",
        surface=SUMMARY,
        asserts=(
            "Last traded price, the mean analyst price target, the gap between "
            "them as target/price - 1, the number of estimates behind it, and "
            "'a thin basis' below THIN_ANALYST_COUNT (5)."
        ),
        made_true_by="stock_summary:_sentence_target",
        checked_by=(
            "tests/test_stock_summary.py::test_target_sentence_states_the_gap_and_the_analyst_count",
        ),
    ),
    Claim(
        id="summary.peers",
        surface=SUMMARY,
        asserts=(
            "Its rank on composite among the nearest sector names by market cap "
            "plus itself, and the best peer's composite."
        ),
        made_true_by="stock_summary:_sentence_peers",
        checked_by=(
            "tests/test_stock_summary.py::test_peer_sentence_counts_stocks_that_outrank_it",
        ),
    ),
    Claim(
        id="summary.flags",
        surface=SUMMARY,
        asserts=(
            "Which of the value-trap, growth-trap, Beneish and channel-stuffing "
            "flags fired, with trap severity out of 100 - or that none fired."
        ),
        made_true_by="stock_summary:_sentence_flags",
        checked_by=(
            "tests/test_stock_summary.py::test_absence_of_flags_is_stated_explicitly",
        ),
    ),
    Claim(
        id="summary.confidence",
        surface=SUMMARY,
        asserts=(
            "How many of the stock's applicable metrics it has values for (35 for a "
            "bank-like stock, 41 otherwise - the same count the composite's coverage "
            "discount reads), which categories could not be scored and were "
            "reweighted away, whether filings are flagged stale and how old, and "
            "whether reported and normalised EPS disagree."
        ),
        made_true_by="stock_summary:_sentence_confidence",
        checked_by=(
            "tests/test_stock_summary.py::test_metric_coverage_is_stated",
            "tests/test_claims_register.py::test_confidence_metric_count_is_the_discount_coverage",
        ),
        caveat=(
            "Fixed 2026-10-07 (T0b). 'rests on N of M metrics' used to count a "
            "hard-coded 18-metric list, which is NOT the applicable-metric coverage "
            "the coverage discount reads; 62 stocks read under 80% on that basis and "
            "3 were discounted. The engine now emits applicable coverage "
            "(`factor_engine.applicable_coverage`) and the page publishes it as "
            "`stock_detail[t].cov`; `metric_count`/`metric_total` carry the same two "
            "numbers."
        ),
    ),
    Claim(
        id="summary.earnings",
        surface=SUMMARY,
        asserts=(
            "The next reporting date or window, its horizon expressed relative to "
            "**this run** rather than the reader's clock, and whether the date is "
            "a provider estimate. A date at or before the run date is dropped."
        ),
        made_true_by="stock_summary:_sentence_earnings",
        checked_by=(
            "tests/test_earnings_date.py::test_horizon_is_anchored_to_the_run_not_the_reader",
            "tests/test_earnings_date.py::test_estimated_date_is_labelled",
        ),
    ),

    # --- the generated methodology page ---------------------------------
    Claim(
        id="overview.composite_is_cardinal",
        surface=OVERVIEW,
        asserts=(
            "Step 5: the composite is the cardinal weighted average of the "
            "category scores and is the ranking key; the universe percentile is "
            "the separate Composite_Pct column, for display only. Replaces the "
            "pre-2026-10-07 claim that the composite was 'converted to a "
            "cross-sectional percentile rank ... a score of 95 means better than "
            "95% of stocks', which contradicted the same page's Limitation 8."
        ),
        made_true_by="run_screener:build_screener_overview",
        checked_by=(
            "tests/test_claims_register.py::test_overview_does_not_contradict_itself_on_the_composite",
            "tests/test_claims_register.py::test_overview_step5_describes_a_cardinal_composite",
        ),
        detect=r"The composite is cardinal, and it is not a percentile",
    ),
    Claim(
        id="overview.coverage_discount",
        surface=OVERVIEW,
        asserts=(
            "Step 5 states the coverage discount as a step applied after the "
            "weighted average, with its threshold and rate read from "
            "config.yaml, and names the denominator it uses - the metrics "
            "applicable to that stock - distinguishing it from the drilldown's "
            "fixed 18-metric provenance badge."
        ),
        made_true_by="run_screener:build_screener_overview",
        checked_by=(
            "tests/test_claims_register.py::test_overview_states_the_coverage_discount_from_config",
        ),
        detect=r"coverage discount described under Data Quality Safeguards",
    ),
    Claim(
        id="overview.limitation8",
        surface=OVERVIEW,
        asserts=(
            "Limitation 8: Composite is cardinal, Composite_Pct is the percentile, "
            "and the reader is told not to confuse them. This was already correct "
            "before 2026-10-07; Step 5 now agrees with it."
        ),
        made_true_by="run_screener:build_screener_overview",
        checked_by=(
            "tests/test_claims_register.py::test_overview_does_not_contradict_itself_on_the_composite",
        ),
        detect=r"Do not read the cardinal Composite as a percentile",
    ),
    Claim(
        id="overview.effective_weights",
        surface=OVERVIEW,
        asserts=(
            "The printed category weights are configured defaults; the "
            "volatility-regime adjustment and missing-data redistribution move "
            "them, and the drilldown shows the weight each score was actually "
            "multiplied by."
        ),
        made_true_by="run_screener:build_screener_overview",
        checked_by=(
            "tests/test_overview_claims.py::test_listed_weights_match_config_exactly",
            "tests/test_weight_transparency.py::test_contributions_sum_to_the_composite",
        ),
        caveat=(
            "True at category level. **Not** true at metric level: the drilldown "
            "prints generic configured metric weights where the engine used bank, "
            "Piotroski-conditional or renormalised ones - 333 of 4,010 "
            "stock-category pairs across 275 of 502 stocks on 2026-10-07. "
            "Defect 1. Fixed 2026-10-07 (T0b): the page now prints the weights the "
            "engine used."
        ),
    ),
    # --- the drilldown's workings (JS, rendered from the payload) ---------
    Claim(
        id="drilldown.metric_weights",
        surface=DRILLDOWN,
        asserts=(
            "The weight beside each metric is the weight this stock's category score "
            "was actually built with - bank, Piotroski-conditional or generic, rescaled "
            "to the metrics that have data - and percentile x weight adds up to the "
            "category score shown."
        ),
        made_true_by="factor_engine:metric_weight_profiles",
        checked_by=(
            "tests/test_calculation_reproducibility.py::test_live_payload_reproduces_every_category_score_and_composite",
            "tests/test_calculation_reproducibility.py::test_category_scores_reproduce_from_the_published_tables",
            "tests/test_dashboard_browser.py::test_bank_valuation_workings_use_bank_weights_and_add_up",
        ),
        caveat=(
            "Fixed 2026-10-07 (T0b). Until then the page printed the generic weight for every stock: wrong "
            "for 275 of 502. The build now refuses to publish a payload whose scores do "
            "not rebuild from its own weights."
        ),
    ),
    Claim(
        id="drilldown.composite_chain",
        surface=DRILLDOWN,
        asserts=(
            "Category points add up to a figure; a coverage discount, when the stock has "
            "values for fewer than the threshold share of its applicable metrics, reduces "
            "it; the result is the composite shown."
        ),
        made_true_by="factor_engine:compute_composite",
        checked_by=(
            "tests/test_calculation_reproducibility.py::test_composite_and_points_reproduce_including_the_coverage_discount",
            "tests/test_dashboard_browser.py::test_composite_chain_sums_for_a_discounted_stock",
        ),
    ),
    # --- the context layer (2026-10-08, plan/context-layer.md): shown, never scored ---
    Claim(
        id="context.expected_move",
        surface=DRILLDOWN,
        asserts=(
            "'Before you decide' gives the options-implied move as the at-the-money call plus "
            "put (mid quotes) divided by the price, on the first expiry after a report due "
            "within 60 days, else the expiry nearest 30 days; quotes that are missing or too "
            "wide give no number."
        ),
        made_true_by="context_signals:options_context",
        checked_by=(
            "tests/test_context_layer.py::test_expected_move_is_the_atm_straddle_over_the_price",
            "tests/test_context_layer.py::test_expiry_spans_a_nearby_report",
            "tests/test_context_layer.py::test_stale_or_wide_quotes_give_no_move",
        ),
    ),
    Claim(
        id="context.rate_sensitivity",
        surface=DRILLDOWN,
        asserts=(
            "A stock's sensitivity to interest rates is the slope of its daily return on the "
            "daily change in the 10-year Treasury yield over the past ~13 months, per +1 "
            "percentage point (shown per +0.10 point), with the share of daily swings it explains."
        ),
        made_true_by="context_signals:rate_sensitivity",
        checked_by=("tests/test_context_layer.py::test_rate_beta_recovers_a_known_slope",),
    ),
    Claim(
        id="context.insider_trades",
        surface=DRILLDOWN,
        asserts=(
            "Insider buying and selling counts open-market purchases and sales only, over the "
            "last 90 days; grants, gifts and option exercises are left out."
        ),
        made_true_by="insider_activity:summarise_rows",
        checked_by=(
            "tests/test_context_layer.py::test_grants_and_exercises_are_not_purchases",
            "tests/test_context_layer.py::test_ninety_day_summary_and_cluster",
        ),
    ),
    Claim(
        id="context.insider_plan",
        surface=DRILLDOWN,
        asserts=(
            "Plan marks a sale the Form 4 reports under a Rule 10b5-1 trading plan; the share of "
            "sales on pre-set plans is shown only where the source carries that flag (the SEC), "
            "never as 0% from a source that does not."
        ),
        made_true_by="insider_activity:rows_from_sec",
        checked_by=(
            "tests/test_context_layer.py::test_sec_rows_keep_open_market_trades_with_plan_flag_and_filing_link",
            "tests/test_context_layer.py::test_planned_sales_are_summarised_and_unknown_stays_unknown",
        ),
    ),
    Claim(
        id="context.track_record",
        surface=DRILLDOWN,
        asserts=(
            "The track record holds the ranking's top 25 in equal weights, rebalanced at the "
            "first comparable run of each month, entering at the close of the first trading "
            "day on or after the run, with dividends and without costs; the benchmark is RSP."
        ),
        made_true_by="track_record:build",
        checked_by=(
            "tests/test_context_layer.py::test_basket_return_matches_hand_arithmetic",
            "tests/test_context_layer.py::test_entry_is_never_before_the_run",
            "tests/test_context_layer.py::test_rebalances_on_the_first_run_of_each_month",
        ),
    ),
    Claim(
        id="context.sahm",
        surface=DRILLDOWN,
        asserts="The Sahm indicator is the 3-month average unemployment rate minus its low over the prior 12 months.",
        made_true_by="market_context:sahm_indicator",
        checked_by=("tests/test_context_layer.py::test_sahm_indicator_definition",),
    ),
    Claim(
        id="drilldown.row_equation",
        surface=DRILLDOWN,
        asserts=(
            "The Calculation line shown when a metric row in the workings is opened - the "
            "stock's reported figures put through the formula, '= value' - gives the value "
            "that was scored. Where it ends in an arrow rather than '=', it lists the real "
            "inputs of a calculation with steps one line cannot carry."
        ),
        made_true_by="metric_lineage:EQUATIONS",
        checked_by=(
            "tests/test_metric_lineage.py::test_the_equation_on_the_row_gives_the_value_that_was_scored",
            "tests/test_metric_lineage.py::test_every_weighted_metric_has_a_line_on_the_row",
            "tests/test_metric_lineage.py::test_template_slots_name_published_inputs",
            "tests/test_dashboard_navigation.py::test_every_metric_row_shows_its_own_numbers",
        ),
    ),
    Claim(
        id="compare.composite_gap",
        surface=DRILLDOWN,
        asserts=(
            "In the side-by-side view, the per-category differences in points - plus a "
            "coverage-discount line where one of the two stocks is discounted - add up to "
            "the gap in composite between the two, rounding aside."
        ),
        made_true_by="factor_engine:compute_composite",
        checked_by=(
            "tests/test_calculation_reproducibility.py::test_points_add_up_to_the_composite_for_every_undiscounted_stock",
            "tests/test_calculation_reproducibility.py::test_a_discounted_stocks_residual_is_its_coverage_discount",
            "tests/test_calculation_reproducibility.py::test_the_gap_lines_reconcile_for_every_pair_with_the_top_stock",
            "tests/test_dashboard_navigation.py::test_compare_lines_up_scores_and_reconciles_the_gap",
        ),
        # "Rounding aside" is part of the claim, not a caveat on it: points are published to
        # 2dp, so eight lines can differ from the gap by up to ~0.09 for an undiscounted pair.
    ),
    Claim(
        id="drilldown.inputs_rebuild",
        surface=DRILLDOWN,
        asserts=(
            "Where a metric row says it was 'rebuilt from the inputs above', the figures "
            "listed, put through the formula shown, give the value that was scored."
        ),
        made_true_by="metric_lineage:RECOMPUTE",
        checked_by=(
            "tests/test_metric_lineage.py::test_the_published_inputs_rebuild_the_published_value",
            "tests/test_metric_lineage.py::test_stocks_that_do_not_rebuild_are_flagged_not_hidden",
        ),
        caveat=(
            "T2 covers the 24 metrics in metric_lineage.RECOMPUTE; series-based and provider-ratio "
            "metrics say so instead. A stock whose inputs do not rebuild its value is "
            "flagged on the page, never shown with a formula that fails."
        ),
    ),
    Claim(
        id="drilldown.peer_rank",
        surface=DRILLDOWN,
        asserts=(
            "'Ranked Nth of M in <sector>' is the stock's position among the stocks in its "
            "sector that have a value for the metric (the whole universe where fewer than "
            "the minimum have one), and the percentile beside it is that rank."
        ),
        made_true_by="factor_engine:compute_sector_percentiles",
        checked_by=(
            "tests/test_metric_lineage.py::test_percentiles_reproduce_from_the_published_peer_values",
            "tests/test_metric_lineage.py::test_sector_stats_agree_with_the_raw_values",
        ),
    ),
    Claim(
        id="drilldown.piotroski_beneish_parts",
        surface=DRILLDOWN,
        asserts=(
            "The nine Piotroski signals listed add up to the score; the eight Beneish "
            "indices, times their published weights plus the constant, give the M-score."
        ),
        made_true_by="factor_engine:_beneish_parts",
        checked_by=(
            "tests/test_metric_lineage.py::test_piotroski_signals_add_up_to_the_score",
            "tests/test_metric_lineage.py::test_beneish_indices_rebuild_the_m_score",
        ),
    ),
)


# ---------------------------------------------------------------------------
# Statements that must appear nowhere
# ---------------------------------------------------------------------------
# Unlike CLAIMS, which enumerates listed surfaces, these are checked against
# every published artifact. Each one shipped to the live public site.

@dataclass(frozen=True)
class Forbidden:
    pattern: str
    why: str
    fixed: str = ""


FORBIDDEN: tuple[Forbidden, ...] = (
    Forbidden(
        pattern=r"composite of [\d.]+ is a percentile",
        why=("The drilldown's first sentence for all 502 stocks. Composite is "
             "cardinal; this told the stock ranked 1st that it scored above 74% "
             "of the universe."),
        fixed="2026-10-07 (T0a)",
    ),
    Forbidden(
        pattern=r"score of 95 means [\"']?better than 95%",
        why=("README and the generated methodology page's Step 5. Same error, "
             "stated as a general rule for reading any composite."),
        fixed="2026-10-07 (T0a)",
    ),
    Forbidden(
        pattern=r"raw composite is then converted to a cross-sectional percentile",
        why=("Step 5 of the generated methodology page - the sentence a student "
             "reads to learn what the headline number means."),
        fixed="2026-10-07 (T0a)",
    ),
    Forbidden(
        pattern=r"`Composite` is a percentile rank, not the weighted sum",
        why=("plan/investor-profiles.md told a future session to add a "
             "client-side percentile transform, which would have stopped the "
             "recompute reproducing the engine's own published numbers."),
        fixed="2026-10-07 (T0a)",
    ),
)


# ---------------------------------------------------------------------------
# Helpers used by the tests and by scripts/check_published_claims.py
# ---------------------------------------------------------------------------

def claims_for(surface: str) -> tuple[Claim, ...]:
    return tuple(c for c in CLAIMS if c.surface == surface)


def claim(claim_id: str) -> Claim:
    for c in CLAIMS:
        if c.id == claim_id:
            return c
    raise KeyError(claim_id)


def registered_builders() -> set[str]:
    """``{"_sentence_rank", ...}`` - the stock_summary functions with a claim."""
    out = set()
    for c in CLAIMS:
        if c.surface != SUMMARY:
            continue
        _, _, qualname = c.made_true_by.partition(":")
        out.add(qualname)
    return out


def forbidden_hits(text: str) -> list[Forbidden]:
    """Every FORBIDDEN pattern present in ``text``."""
    import re
    return [f for f in FORBIDDEN if re.search(f.pattern, text)]


def open_caveats() -> tuple[Claim, ...]:
    """Claims carrying a known, recorded limitation - the T0b work list."""
    return tuple(c for c in CLAIMS if c.caveat)
