#!/usr/bin/env bash
# deploy_dashboard.sh — Push latest dashboard.html to GitHub Pages
# Usage: 
#   bash deploy_dashboard.sh
# 
# Configuration:
#   Set DASHBOARD_REPO environment variable to override the default repository path:
#   export DASHBOARD_REPO=/path/to/your/dashboard/repo
#   bash deploy_dashboard.sh

set -euo pipefail

# ---- Configuration ----
SCREENER_DIR="$(cd "$(dirname "$0")" && pwd)"

# Default path (for the original user's setup)
DEFAULT_DASHBOARD_REPO="/c/Users/Caleb/OneDrive - Dordt University/Desktop/screener-dashboard"

# Use environment variable if set, otherwise use default
DASHBOARD_REPO="${DASHBOARD_REPO:-$DEFAULT_DASHBOARD_REPO}"

SOURCE="$SCREENER_DIR/dashboard.html"
TARGET="$DASHBOARD_REPO/index.html"

SOURCE_DATA="$SCREENER_DIR/dashboard_data.js"
TARGET_DATA="$DASHBOARD_REPO/dashboard_data.js"

# ---- Preflight checks ----
if [ ! -f "$SOURCE" ]; then
    echo "ERROR: dashboard.html not found at: $SOURCE"
    echo "Run 'python generate_dashboard.py' first."
    exit 1
fi

if [ ! -d "$DASHBOARD_REPO/.git" ]; then
    echo "ERROR: Dashboard repo not found at: $DASHBOARD_REPO"
    echo ""
    echo "Please set the DASHBOARD_REPO environment variable:"
    echo "  export DASHBOARD_REPO=/path/to/screener-dashboard"
    echo "  bash deploy_dashboard.sh"
    echo ""
    echo "Or create the default folder (see setup instructions)."
    exit 1
fi

# ---- Deploy ----
cd "$DASHBOARD_REPO"

# Sync with remote first (Screener-1 pushes to the same remote in an earlier step)
git pull --rebase origin main

echo "Copying dashboard.html -> index.html ..."
cp "$SOURCE" "$TARGET"

# Copy companion data file if present (generated by lazy-loading split)
if [ -f "$SOURCE_DATA" ]; then
    echo "Copying dashboard_data.js ..."
    cp "$SOURCE_DATA" "$TARGET_DATA"
else
    echo "WARNING: dashboard_data.js not found — dashboard may show empty data"
fi

# Check if there are actually changes (either HTML or data)
DATA_CHANGED=false
if [ -f "$TARGET_DATA" ] && ! git diff --quiet dashboard_data.js 2>/dev/null; then
    DATA_CHANGED=true
fi
if git diff --quiet index.html 2>/dev/null && [ "$DATA_CHANGED" = "false" ]; then
    echo "No changes detected. Dashboard is already up to date."
    exit 0
fi

TIMESTAMP=$(date '+%Y-%m-%d %H:%M')
FILES_TO_ADD="index.html"
[ -f "$TARGET_DATA" ] && FILES_TO_ADD="$FILES_TO_ADD dashboard_data.js"
git add $FILES_TO_ADD
git commit -m "Update dashboard — $TIMESTAMP"
git push origin main

echo ""
echo "Deployed! Site will update in ~60 seconds at:"
echo "  https://calebsmit.github.io/screener-dashboard/"
